# Generated by Django 3.0.8 on 2020-09-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0002_posts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
