# Generated by Django 3.0.8 on 2020-09-07 16:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0004_comment_handbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
